name: OasisSky
main: oasis.oasissky.OasisSky
version: 1.0
description: Oasis SkyBlock plugin
author: Paxination
depend: [WorldEdit, WorldGuard, Multiverse-Core]
commands:

  skyblock:
    description: Main Skyblock command
    usage: "Usage: /<command>"
    permission: oasissky.user.skyblock
    permission-message: You don't have permissions for <permission>